# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-20 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_training', '0002_auto_20181219_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_session',
            name='trainingId',
            field=models.ManyToManyField(to='ts_training.Training_spec'),
        ),
    ]
