# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-18 21:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ts_training', '0003_auto_20181220_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planned_session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slots', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='lead', to='ts_training.Person')),
            ],
        ),
        migrations.AlterField(
            model_name='icon',
            name='iconName',
            field=models.CharField(max_length=25, verbose_name='Item Name'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='iconRef',
            field=models.CharField(max_length=25, verbose_name='Font Awesome Icon for Item'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='itemType',
            field=models.CharField(choices=[('PAGE', 'Page'), ('CAT', 'Training Category')], max_length=15, verbose_name='Item Type'),
        ),
        migrations.AlterField(
            model_name='icon',
            name='weight',
            field=models.IntegerField(verbose_name='Item Number'),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='trainingId',
            field=models.ManyToManyField(to='ts_training.Training_spec'),
        ),
        migrations.AlterField(
            model_name='training_spec',
            name='trainingId',
            field=models.DecimalField(decimal_places=2, max_digits=4, unique=True, verbose_name='Spec ID Number'),
        ),
        migrations.AlterField(
            model_name='training_spec',
            name='trainingTitle',
            field=models.CharField(max_length=50, verbose_name='Training Title'),
        ),
        migrations.AddField(
            model_name='planned_session',
            name='plannedID',
            field=models.ManyToManyField(to='ts_training.Training_spec'),
        ),
    ]
