# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-18 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_training', '0004_auto_20200318_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planned_session',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='planned_session',
            name='plannedID',
        ),
        migrations.AddField(
            model_name='training_session',
            name='occured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='trainingId',
            field=models.ManyToManyField(to='ts_training.Training_spec'),
        ),
        migrations.DeleteModel(
            name='Planned_session',
        ),
    ]
