# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-03-24 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("ts_training", "0007_auto_20200319_2200"),
    ]

    operations = [
        migrations.AddField(
            model_name="planned_session",
            name="signed_up",
            field=models.ManyToManyField(
                related_name="signed_up", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="planned_session",
            name="trainingId",
            field=models.ManyToManyField(to="ts_training.Training_spec"),
        ),
        migrations.AlterField(
            model_name="training_session",
            name="trainingId",
            field=models.ManyToManyField(to="ts_training.Training_spec"),
        ),
    ]
