# Generated by Django 3.0.4 on 2020-03-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ts_training', '0011_auto_20200325_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='planned_session',
            name='signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planned_session',
            name='trainingId',
            field=models.ManyToManyField(to='ts_training.Training_spec'),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='trainingId',
            field=models.ManyToManyField(to='ts_training.Training_spec'),
        ),
    ]
